cmake_minimum_required(VERSION 3.20)
project(MyProject VERSION 1.0 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
add_executable(main src/main.cpp)
add_executable(sem src/sem.cpp)
add_executable(sem2 src/sem2.cpp)
add_executable(sem1_2 src/sem1_2.cpp)
add_executable(sem1_3 src/sem1_3.cpp)