# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nigelvoid/projects/my_cpp_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nigelvoid/projects/my_cpp_project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nigelvoid/projects/my_cpp_project/CMakeFiles /home/nigelvoid/projects/my_cpp_project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nigelvoid/projects/my_cpp_project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named sem

# Build rule for target.
sem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sem
.PHONY : sem

# fast build rule for target.
sem/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sem.dir/build.make CMakeFiles/sem.dir/build
.PHONY : sem/fast

#=============================================================================
# Target rules for targets named sem2

# Build rule for target.
sem2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sem2
.PHONY : sem2

# fast build rule for target.
sem2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sem2.dir/build.make CMakeFiles/sem2.dir/build
.PHONY : sem2/fast

#=============================================================================
# Target rules for targets named sem1_2

# Build rule for target.
sem1_2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sem1_2
.PHONY : sem1_2

# fast build rule for target.
sem1_2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sem1_2.dir/build.make CMakeFiles/sem1_2.dir/build
.PHONY : sem1_2/fast

#=============================================================================
# Target rules for targets named sem1_3

# Build rule for target.
sem1_3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sem1_3
.PHONY : sem1_3

# fast build rule for target.
sem1_3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sem1_3.dir/build.make CMakeFiles/sem1_3.dir/build
.PHONY : sem1_3/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/sem.o: src/sem.cpp.o
.PHONY : src/sem.o

# target to build an object file
src/sem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sem.dir/build.make CMakeFiles/sem.dir/src/sem.cpp.o
.PHONY : src/sem.cpp.o

src/sem.i: src/sem.cpp.i
.PHONY : src/sem.i

# target to preprocess a source file
src/sem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sem.dir/build.make CMakeFiles/sem.dir/src/sem.cpp.i
.PHONY : src/sem.cpp.i

src/sem.s: src/sem.cpp.s
.PHONY : src/sem.s

# target to generate assembly for a file
src/sem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sem.dir/build.make CMakeFiles/sem.dir/src/sem.cpp.s
.PHONY : src/sem.cpp.s

src/sem1_2.o: src/sem1_2.cpp.o
.PHONY : src/sem1_2.o

# target to build an object file
src/sem1_2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sem1_2.dir/build.make CMakeFiles/sem1_2.dir/src/sem1_2.cpp.o
.PHONY : src/sem1_2.cpp.o

src/sem1_2.i: src/sem1_2.cpp.i
.PHONY : src/sem1_2.i

# target to preprocess a source file
src/sem1_2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sem1_2.dir/build.make CMakeFiles/sem1_2.dir/src/sem1_2.cpp.i
.PHONY : src/sem1_2.cpp.i

src/sem1_2.s: src/sem1_2.cpp.s
.PHONY : src/sem1_2.s

# target to generate assembly for a file
src/sem1_2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sem1_2.dir/build.make CMakeFiles/sem1_2.dir/src/sem1_2.cpp.s
.PHONY : src/sem1_2.cpp.s

src/sem1_3.o: src/sem1_3.cpp.o
.PHONY : src/sem1_3.o

# target to build an object file
src/sem1_3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sem1_3.dir/build.make CMakeFiles/sem1_3.dir/src/sem1_3.cpp.o
.PHONY : src/sem1_3.cpp.o

src/sem1_3.i: src/sem1_3.cpp.i
.PHONY : src/sem1_3.i

# target to preprocess a source file
src/sem1_3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sem1_3.dir/build.make CMakeFiles/sem1_3.dir/src/sem1_3.cpp.i
.PHONY : src/sem1_3.cpp.i

src/sem1_3.s: src/sem1_3.cpp.s
.PHONY : src/sem1_3.s

# target to generate assembly for a file
src/sem1_3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sem1_3.dir/build.make CMakeFiles/sem1_3.dir/src/sem1_3.cpp.s
.PHONY : src/sem1_3.cpp.s

src/sem2.o: src/sem2.cpp.o
.PHONY : src/sem2.o

# target to build an object file
src/sem2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sem2.dir/build.make CMakeFiles/sem2.dir/src/sem2.cpp.o
.PHONY : src/sem2.cpp.o

src/sem2.i: src/sem2.cpp.i
.PHONY : src/sem2.i

# target to preprocess a source file
src/sem2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sem2.dir/build.make CMakeFiles/sem2.dir/src/sem2.cpp.i
.PHONY : src/sem2.cpp.i

src/sem2.s: src/sem2.cpp.s
.PHONY : src/sem2.s

# target to generate assembly for a file
src/sem2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sem2.dir/build.make CMakeFiles/sem2.dir/src/sem2.cpp.s
.PHONY : src/sem2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... sem"
	@echo "... sem1_2"
	@echo "... sem1_3"
	@echo "... sem2"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/sem.o"
	@echo "... src/sem.i"
	@echo "... src/sem.s"
	@echo "... src/sem1_2.o"
	@echo "... src/sem1_2.i"
	@echo "... src/sem1_2.s"
	@echo "... src/sem1_3.o"
	@echo "... src/sem1_3.i"
	@echo "... src/sem1_3.s"
	@echo "... src/sem2.o"
	@echo "... src/sem2.i"
	@echo "... src/sem2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

